# Generated by Django 5.0.1 on 2024-02-16 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('cost', models.IntegerField(default=0)),
                ('color', models.TextField(choices=[('BLACK', 'Чёрный'), ('WHITE', 'Белый'), ('BLUE', 'Синий'), ('RED', 'Красный'), ('GREEN', 'Зелёный'), ('PURPLE', 'Фиолетовый')], default='BLACK')),
            ],
        ),
        migrations.CreateModel(
            name='WearSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WearComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('wear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wear')),
            ],
        ),
        migrations.AddField(
            model_name='wear',
            name='size',
            field=models.ManyToManyField(to='api.wearsize'),
        ),
        migrations.AddField(
            model_name='wear',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weartype'),
        ),
    ]
