# Generated by Django 5.0.1 on 2024-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wear',
            name='image',
            field=models.ImageField(null=True, upload_to='wear_images'),
        ),
    ]
