# Generated by Django 5.0.2 on 2024-03-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_wear_id_wearcomment_wear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwear',
            name='info_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wear',
            name='info_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
