# Generated by Django 5.0.2 on 2024-03-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historicalwear_info_text_wear_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearcomment',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
