# Generated by Django 5.0.2 on 2024-03-11 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wearcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearcomment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 11)),
        ),
    ]
